### ISSUE TITLE
MapView always draws annotations in top-right corner of a map

### ISSUE THREAD

**Issue by alexwald** [applidium/ADClusterMapView#11]
everytime I load the mapview (even on the demo map), it would display a bunch of annotations in the top-right corner, please see the screenshot attached
![Screen Shot 2013-03-13 at 12 51 09 PM](https://f.cloud.github.com/assets/646637/253476/895dcc80-8bd4-11e2-8b7c-738399e28953.png)

**Comment by samuel-gallet** [comment]
Fix with the version update to 1.2
