### ISSUE TITLE
Custom MKAnnotation image rendering problem after zooms in/out

### ISSUE THREAD

**Issue by Narayane** [applidium/ADClusterMapView#28]
Hi,
I have a little problem after multiple zooms in and/or out.
My application has a search view which allows to see a ride between two locations.

![default](https://f.cloud.github.com/assets/4921308/1101710/6fb34020-17da-11e3-83b6-2ef5696fcb5c.PNG)

After a few zooms in/out and a refocusing on the ride to be in the same view than previously, I have this result.

![after_zooms](https://f.cloud.github.com/assets/4921308/1101715/c032e47e-17da-11e3-9ccc-37892037b978.PNG)

As you can see, departure marker (initially gray) is replaced by a station marker and third station marker is replaced by arrival marker.

I do not have this problem with a basic MKMapView.

Thanks for help.

**Comment by samuel-gallet** [comment]
Fix with the version update to 1.2
