### ISSUE TITLE
High level zoom out crash

### ISSUE THREAD

**Issue by Narayane** [applidium/ADClusterMapView#29]
Hi,
I have a problem relative to zoom out level.
From zoom out level allowing seeing all Europe on map, if I continue to zoom out, I have consistently the same crash :

*** Assertion failure in -[ADClusterAnnotation originalAnnotations], ../ADClusterMapView/ADClusterAnnotation.m:59

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This annotation should have a cluster assigned!'

*** First throw call stack:

(0x32d1c2a3 0x3a97697f 0x32d1c15d 0x335f1ab7 0xb3ad9 0x835bd 0xb599b 0x33b38045 0x33b37e71 0x33b34a87 0x33b36ef9 0x33b3510d 0x33b4838d 0x33b484e9 0x33b40567 0x34c41d89 0x34c093f5 0x34df6a39 0x34b2d82f 0x34b2c293 0x34b371e7 0x34b36db3 0x34b24801 0x34b2411b 0x367e05a3 0x367e01d3 0x32cf1173 0x32cf1117 0x32ceff99 0x32c62ebd 0x32c62d49 0x367df2eb 0x34b78301 0x80a35 0x3adadb20)

libc++abi.dylib: terminate called throwing an exception

I have kept default values for numberOfClustersInMapView and clusterDiscriminatorPowerForMapView parameters

A screenshot of the last valid zoom out level

![img_0004](https://f.cloud.github.com/assets/4921308/1121250/03dece56-1abd-11e3-83ce-ab2031e45154.PNG)

**Comment by dorjeozer** [comment]
Still working with this one?

**Comment by samuel-gallet** [comment]
Fix with the version update to 1.2
