### ISSUE TITLE
Getting wrong number of annotations from MKAnnotationView

### ISSUE THREAD

**Issue by IDBasso** [applidium/ADClusterMapView#31]
Hi all,

I want to show the amount of annotations that a clusterAnnotation is holding.

![foto](https://f.cloud.github.com/assets/2582383/1241804/7d41cf7c-2a27-11e3-81f5-642a1d3a9162.PNG)

Here the code:

        - (MKAnnotationView *)mapView:(ADClusterMapView *)mapView viewForClusterAnnotation:(id<MKAnnotation>)annotation {

        if ([annotation isKindOfClass:[MKUserLocation class]])
        return nil;

      MKAnnotationView * pinView = (MKAnnotationView *)[mapView dequeueReusableAnnotationViewWithIdentifier:@"ADMapCluster"];
    if (!pinView) {
        pinView = [[MKAnnotationView alloc] initWithAnnotation:annotation reuseIdentifier:@"ADMapCluster"];
        pinView.image = [UIImage imageNamed:@"map-markers"];
        UILabel *countLabel = [[UILabel alloc] initWithFrame:CGRectMake(2, 5, 25, 20)];
        countLabel.textAlignment = NSTextAlignmentCenter;
        [countLabel setTag:2];
        countLabel.text = [NSString stringWithFormat:@"%d",[[(ADClusterAnnotation*)pinView.annotation originalAnnotations]count]];
        countLabel.font = [UIFont fontWithName:@"Avenir-Book" size:10];
        [pinView addSubview:countLabel];

    }
    else {
       pinView.annotation = annotation;
       [((UILabel*)[pinView viewWithTag:2]) setText:[NSString stringWithFormat:@"%d", [[(ADClusterAnnotation*)annotation originalAnnotations] count]]];

        
        [((UILabel*)[pinView viewWithTag:2]) setNeedsDisplay];
    }
    return pinView;
}

Unfortunately I'm getting wrong numbers and I'm not sure [[(ADClusterAnnotation*)annotation originalAnnotations] count]  is the method I should call here. Any idea what is wrong with my code? 

thankfully, 
Diana

**Comment by samuel-gallet** [comment]
Fix with the version update to 1.2
