### ISSUE TITLE
removeAnnotations not working

### ISSUE THREAD

**Issue by pomello** [applidium/ADClusterMapView#40]
I tried to invoke removeAnnotations but all the pin stays in the mapview.
to reproduce it just add to the demo code the following lines:

## At the end of viewDidLog add
[self performSelector:@selector(removeAll) withObject:nil afterDelay:5];

## and the add:

-(void)removeAll {
    NSLog(@"Remove All PINs");
    NSArray *list = [self.mapView annotations];
    [self.mapView removeAnnotations:list ];
}

**Comment by hkellaway** [comment]
Just ran into this issue myself and the supplied solution unfortunately doesn't work for me :/

**Comment by samuel-gallet** [comment]
Fix with the version update to 1.2
