### ISSUE TITLE
Crash when zooming to kADCoordinate2DOffscreen

### ISSUE THREAD

**Issue by vrujbr** [applidium/ADClusterMapView#44]
When you zoom out you get to show a few annotations on kADCoordinate2DOffscreen (almost north pole) from both pools and call viewForAnnoattion.
If you happen to have in this method [clusterAnnotation originalAnnotations] code, it crashes, cause it executes NSAssert(self.cluster != nil, @"This annotation should have a cluster assigned!");. Obviously, there`s no cluster and nothing cause this is not a real annotation, just a prototype from some pool.
Fix: Setting #define kADCoordinate2DOffscreen kCLLocationCoordinate2DInvalid in ADClusterAnnotation fixes that, not sure if it doesn't cause problems elsewhere (as discussed in another issue).
Workaround: check if annotation is not on kADCoordinate2DOffscreen before calling originalAnnotations.

**Comment by samuel-gallet** [comment]
Fix with the version update to 1.2
