### ISSUE TITLE
delegate is not weak

### ISSUE THREAD

**Issue by sareninden** [applidium/ADClusterMapView#48]
In the ADClusterMapView.m interface part is an secondary delegate declared.
@interface ADClusterMapView () <UIGestureRecognizerDelegate>
{
@private
   id <ADClusterMapViewDelegate> _secondaryDelegate;

This should be weak to prevent retain cycles, currently delegates are retained strongly causing a retain cycle.

suggested code

@interface ADClusterMapView () <UIGestureRecognizerDelegate>
{
@private
    __weak id <ADClusterMapViewDelegate> _secondaryDelegate;

**Comment by Nooba** [comment]
Fixed in version 1.1.1
