### ISSUE TITLE
Annotation behaviour and count for cluster

### ISSUE THREAD

**Issue by architector1** [applidium/ADClusterMapView#52]
First of all thank you for this awesome project. You have done some really great work here!
I tried it a bit and got some nice results, but on the level of usability and graphical details there are still some shortcomings compared for instance to the Photos application by Apple.

-> A small detail which may explain the multiple reports why the number of children is often wrong especially when clustered annotations get split into new clusters:
While zooming in fast a clustered annotation view turns into two or more non clustered annotations and then those annotations "walk" to their correct positions. That's perfect.
But while zooming out those single annotations will change to clustered annotation views first and then "walk" to their mutual position. You can observe this at the Demo project (colours changing).
Same when you zoom in a bit on a clustered annotation which let's say has 5 children. Since I have numbers written on the clusters I see a 5 on my screen. I zoom in until the annotation splits in two parts containing 2 and 3 children. The first annotation will reuse the original cluster annotation, so it has a 5 on it and moves to the new position. The second annotation will be new and has a 3 on it. So you get the impression the new annotations contain 8 children now :-(

To fix this the app should
- leave annotations which will get collapsed as they are until they moved to their mutual point and then exchange them with the clustered annotation.
- after zooming in remove the clustered annotation and show all (visible) children. then move them to their correct position. 

-> A feature which would be really nice is the possibility to add and remove single annotations instead of setting all annotations at once. For instance if you want to show annotations depending on your current position you will get a lot of flickering with the current solution.

-> Scrolling
Small detail: It would be nice if the annotations and clustered annotations would be drawn when they come into the visible area and not after the scrolling is finished.

-> Dynamic cluster amount
The fixed amount of clusters leads to a homogenous distribution of annotation views but once you zoom out very far it's not really good to have still something like 32 annotations sitting almost at the same spot. It would be great if annotations which are overlapping each other get combined to a cluster regardless on the amount of visible clusters on the screen.

-> Cluster creation
Sometimes the selection of annotations chosen to cluster is a bit strange. I have two annotations very close to each other but instead of combining them they would move both very far to other annotations.
Could you please explain the DiscriminationPower? May it help solving this problem?

I would really like to work on this project but unfortunately I hardly have any programming skills.

**Comment by samuel-gallet** [comment]
The children count issue has been fixed and the behaviour requested while scrolling has been implemented.
The other enhancements have been taken into consideration. Thank you
